# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /opt/clion/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/iancu/Desktop/Cormoran

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/iancu/Desktop/Cormoran

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/iancu/Desktop/Cormoran/CMakeFiles /home/iancu/Desktop/Cormoran/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/iancu/Desktop/Cormoran/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Cormoran

# Build rule for target.
Cormoran: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Cormoran
.PHONY : Cormoran

# fast build rule for target.
Cormoran/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cormoran.dir/build.make CMakeFiles/Cormoran.dir/build
.PHONY : Cormoran/fast

builtin/builtin.o: builtin/builtin.c.o

.PHONY : builtin/builtin.o

# target to build an object file
builtin/builtin.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cormoran.dir/build.make CMakeFiles/Cormoran.dir/builtin/builtin.c.o
.PHONY : builtin/builtin.c.o

builtin/builtin.i: builtin/builtin.c.i

.PHONY : builtin/builtin.i

# target to preprocess a source file
builtin/builtin.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cormoran.dir/build.make CMakeFiles/Cormoran.dir/builtin/builtin.c.i
.PHONY : builtin/builtin.c.i

builtin/builtin.s: builtin/builtin.c.s

.PHONY : builtin/builtin.s

# target to generate assembly for a file
builtin/builtin.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cormoran.dir/build.make CMakeFiles/Cormoran.dir/builtin/builtin.c.s
.PHONY : builtin/builtin.c.s

exec/exec.o: exec/exec.c.o

.PHONY : exec/exec.o

# target to build an object file
exec/exec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cormoran.dir/build.make CMakeFiles/Cormoran.dir/exec/exec.c.o
.PHONY : exec/exec.c.o

exec/exec.i: exec/exec.c.i

.PHONY : exec/exec.i

# target to preprocess a source file
exec/exec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cormoran.dir/build.make CMakeFiles/Cormoran.dir/exec/exec.c.i
.PHONY : exec/exec.c.i

exec/exec.s: exec/exec.c.s

.PHONY : exec/exec.s

# target to generate assembly for a file
exec/exec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cormoran.dir/build.make CMakeFiles/Cormoran.dir/exec/exec.c.s
.PHONY : exec/exec.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cormoran.dir/build.make CMakeFiles/Cormoran.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cormoran.dir/build.make CMakeFiles/Cormoran.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cormoran.dir/build.make CMakeFiles/Cormoran.dir/main.c.s
.PHONY : main.c.s

utils/utils.o: utils/utils.c.o

.PHONY : utils/utils.o

# target to build an object file
utils/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cormoran.dir/build.make CMakeFiles/Cormoran.dir/utils/utils.c.o
.PHONY : utils/utils.c.o

utils/utils.i: utils/utils.c.i

.PHONY : utils/utils.i

# target to preprocess a source file
utils/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cormoran.dir/build.make CMakeFiles/Cormoran.dir/utils/utils.c.i
.PHONY : utils/utils.c.i

utils/utils.s: utils/utils.c.s

.PHONY : utils/utils.s

# target to generate assembly for a file
utils/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cormoran.dir/build.make CMakeFiles/Cormoran.dir/utils/utils.c.s
.PHONY : utils/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Cormoran"
	@echo "... builtin/builtin.o"
	@echo "... builtin/builtin.i"
	@echo "... builtin/builtin.s"
	@echo "... exec/exec.o"
	@echo "... exec/exec.i"
	@echo "... exec/exec.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... utils/utils.o"
	@echo "... utils/utils.i"
	@echo "... utils/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

